version: '3.8'
services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "$PORT:8000"
    command: ./scripts/run-dev.sh
    env_file:
      - .env

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 2s
      timeout: 2s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
        db:
          condition: service_healthy
    ports:
      - "4000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      GUNICORN_ACCESS_LOGFILE: /dev/null # Disables logging
    logging:
      driver: none # Disables logging

volumes:
  postgres:
