name: CI

on:
  push:
    branches:
      - main

env:
  DENO_VERSION: 1.20.5

jobs:
  format-and-lint:
    name: Format and lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check Deno formatting
        run: deno fmt --check

      - name: Check Deno linting
        run: deno lint