name: CI

env:
  DENO_VERSION: 1.20.3

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Check deno formatting
        run: deno fmt --check

      - name: Check deno linting
        run: deno lint